name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Handle Next.js Cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Download and install SF Pro fonts
        run: |
          echo "Downloading SF Pro fonts..."
          curl -L https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg -o SF-Pro.dmg

          echo "Mounting DMG file..."
          hdiutil attach SF-Pro.dmg -nobrowse

          echo "Installing SF Pro fonts package..."
          sudo installer -pkg "/Volumes/SFProFonts/SF Pro Fonts.pkg" -target /

          echo "Unmounting DMG..."
          hdiutil detach "/Volumes/SFProFonts" -force

          echo "Listing installed fonts..."
          ls -la /Library/Fonts/SF-Pro*

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
